//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECSMS.Channel.LingTongService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.m1860.com/service/", ConfigurationName="LingTongService.SmsServiceSoap")]
    public interface SmsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.m1860.com/service/query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int query(string name, string hashedpass, string timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.m1860.com/service/submitmsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int submitmsg(string name, string hashedpass, string timestamp, string subphone, string msgsub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.m1860.com/service/changepw", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int changepw(string name, string hashedoldpass, string timestamp, string newpass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsServiceSoapChannel : ECSMS.Channel.LingTongService.SmsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceSoapClient : System.ServiceModel.ClientBase<ECSMS.Channel.LingTongService.SmsServiceSoap>, ECSMS.Channel.LingTongService.SmsServiceSoap {
        
        public SmsServiceSoapClient() {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int query(string name, string hashedpass, string timestamp) {
            return base.Channel.query(name, hashedpass, timestamp);
        }
        
        public int submitmsg(string name, string hashedpass, string timestamp, string subphone, string msgsub) {
            return base.Channel.submitmsg(name, hashedpass, timestamp, subphone, msgsub);
        }
        
        public int changepw(string name, string hashedoldpass, string timestamp, string newpass) {
            return base.Channel.changepw(name, hashedoldpass, timestamp, newpass);
        }
    }
}
