//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECSMS.Channel.LingKaiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LingKaiService.LinkWSSoap")]
    public interface LinkWSSoap {
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WapSend", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.WapSendResponse WapSend(ECSMS.Channel.LingKaiService.WapSendRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportFail", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.GetReportFailResponse GetReportFail(ECSMS.Channel.LingKaiService.GetReportFailRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BatchSend", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.BatchSendResponse BatchSend(ECSMS.Channel.LingKaiService.BatchSendRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Reg", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.RegResponse Reg(ECSMS.Channel.LingKaiService.RegRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdPwd", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.UpdPwdResponse UpdPwd(ECSMS.Channel.LingKaiService.UpdPwdRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdReg", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.UpdRegResponse UpdReg(ECSMS.Channel.LingKaiService.UpdRegRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelSum", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.SelSumResponse SelSum(ECSMS.Channel.LingKaiService.SelSumRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.SendResponse Send(ECSMS.Channel.LingKaiService.SendRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.GetResponse Get(ECSMS.Channel.LingKaiService.GetRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnReg", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.UnRegResponse UnReg(ECSMS.Channel.LingKaiService.UnRegRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeUp", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.ChargeUpResponse ChargeUp(ECSMS.Channel.LingKaiService.ChargeUpRequest request);
        
        // CODEGEN: Generating message contract since element name CorpID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowMessage", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.ShowMessageResponse ShowMessage(ECSMS.Channel.LingKaiService.ShowMessageRequest request);
        
        // CODEGEN: Generating message contract since element name Ver from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVer", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.GetVerResponse GetVer(ECSMS.Channel.LingKaiService.GetVerRequest request);
        
        // CODEGEN: Generating message contract since element name Ver from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdateData", ReplyAction="*")]
        ECSMS.Channel.LingKaiService.GetUpdateDataResponse GetUpdateData(ECSMS.Channel.LingKaiService.GetUpdateDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WapSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WapSend", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.WapSendRequestBody Body;
        
        public WapSendRequest() {
        }
        
        public WapSendRequest(ECSMS.Channel.LingKaiService.WapSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WapSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WebSite;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cell;
        
        public WapSendRequestBody() {
        }
        
        public WapSendRequestBody(string CorpID, string Pwd, string Mobile, string WebSite, string Title, string cell) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.WebSite = WebSite;
            this.Title = Title;
            this.cell = cell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WapSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WapSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.WapSendResponseBody Body;
        
        public WapSendResponse() {
        }
        
        public WapSendResponse(ECSMS.Channel.LingKaiService.WapSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WapSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WapSendResult;
        
        public WapSendResponseBody() {
        }
        
        public WapSendResponseBody(int WapSendResult) {
            this.WapSendResult = WapSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportFailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportFail", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetReportFailRequestBody Body;
        
        public GetReportFailRequest() {
        }
        
        public GetReportFailRequest(ECSMS.Channel.LingKaiService.GetReportFailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportFailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cell;
        
        public GetReportFailRequestBody() {
        }
        
        public GetReportFailRequestBody(string CorpID, string Pwd, string cell) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.cell = cell;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportFailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportFailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetReportFailResponseBody Body;
        
        public GetReportFailResponse() {
        }
        
        public GetReportFailResponse(ECSMS.Channel.LingKaiService.GetReportFailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportFailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetReportFailResult;
        
        public GetReportFailResponseBody() {
        }
        
        public GetReportFailResponseBody(string GetReportFailResult) {
            this.GetReportFailResult = GetReportFailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchSend", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.BatchSendRequestBody Body;
        
        public BatchSendRequest() {
        }
        
        public BatchSendRequest(ECSMS.Channel.LingKaiService.BatchSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BatchSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cell;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SendTime;
        
        public BatchSendRequestBody() {
        }
        
        public BatchSendRequestBody(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.BatchSendResponseBody Body;
        
        public BatchSendResponse() {
        }
        
        public BatchSendResponse(ECSMS.Channel.LingKaiService.BatchSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BatchSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int BatchSendResult;
        
        public BatchSendResponseBody() {
        }
        
        public BatchSendResponseBody(int BatchSendResult) {
            this.BatchSendResult = BatchSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reg", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.RegRequestBody Body;
        
        public RegRequest() {
        }
        
        public RegRequest(ECSMS.Channel.LingKaiService.RegRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CorpName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LinkMan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Memo;
        
        public RegRequestBody() {
        }
        
        public RegRequestBody(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.CorpName = CorpName;
            this.LinkMan = LinkMan;
            this.Tel = Tel;
            this.Mobile = Mobile;
            this.Email = Email;
            this.Memo = Memo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.RegResponseBody Body;
        
        public RegResponse() {
        }
        
        public RegResponse(ECSMS.Channel.LingKaiService.RegResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegResult;
        
        public RegResponseBody() {
        }
        
        public RegResponseBody(int RegResult) {
            this.RegResult = RegResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdPwdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdPwd", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.UpdPwdRequestBody Body;
        
        public UpdPwdRequest() {
        }
        
        public UpdPwdRequest(ECSMS.Channel.LingKaiService.UpdPwdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdPwdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewPwd;
        
        public UpdPwdRequestBody() {
        }
        
        public UpdPwdRequestBody(string CorpID, string Pwd, string NewPwd) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.NewPwd = NewPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdPwdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdPwdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.UpdPwdResponseBody Body;
        
        public UpdPwdResponse() {
        }
        
        public UpdPwdResponse(ECSMS.Channel.LingKaiService.UpdPwdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdPwdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdPwdResult;
        
        public UpdPwdResponseBody() {
        }
        
        public UpdPwdResponseBody(int UpdPwdResult) {
            this.UpdPwdResult = UpdPwdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdRegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdReg", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.UpdRegRequestBody Body;
        
        public UpdRegRequest() {
        }
        
        public UpdRegRequest(ECSMS.Channel.LingKaiService.UpdRegRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdRegRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CorpName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LinkMan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Memo;
        
        public UpdRegRequestBody() {
        }
        
        public UpdRegRequestBody(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.CorpName = CorpName;
            this.LinkMan = LinkMan;
            this.Tel = Tel;
            this.Mobile = Mobile;
            this.Email = Email;
            this.Memo = Memo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdRegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdRegResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.UpdRegResponseBody Body;
        
        public UpdRegResponse() {
        }
        
        public UpdRegResponse(ECSMS.Channel.LingKaiService.UpdRegResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdRegResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdRegResult;
        
        public UpdRegResponseBody() {
        }
        
        public UpdRegResponseBody(int UpdRegResult) {
            this.UpdRegResult = UpdRegResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelSumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelSum", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.SelSumRequestBody Body;
        
        public SelSumRequest() {
        }
        
        public SelSumRequest(ECSMS.Channel.LingKaiService.SelSumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelSumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        public SelSumRequestBody() {
        }
        
        public SelSumRequestBody(string CorpID, string Pwd) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelSumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelSumResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.SelSumResponseBody Body;
        
        public SelSumResponse() {
        }
        
        public SelSumResponse(ECSMS.Channel.LingKaiService.SelSumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelSumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SelSumResult;
        
        public SelSumResponseBody() {
        }
        
        public SelSumResponseBody(int SelSumResult) {
            this.SelSumResult = SelSumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.SendRequestBody Body;
        
        public SendRequest() {
        }
        
        public SendRequest(ECSMS.Channel.LingKaiService.SendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cell;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SendTime;
        
        public SendRequestBody() {
        }
        
        public SendRequestBody(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Content = Content;
            this.Cell = Cell;
            this.SendTime = SendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.SendResponseBody Body;
        
        public SendResponse() {
        }
        
        public SendResponse(ECSMS.Channel.LingKaiService.SendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendResult;
        
        public SendResponseBody() {
        }
        
        public SendResponseBody(int SendResult) {
            this.SendResult = SendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(ECSMS.Channel.LingKaiService.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(string CorpID, string Pwd) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(ECSMS.Channel.LingKaiService.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(string GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnRegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnReg", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.UnRegRequestBody Body;
        
        public UnRegRequest() {
        }
        
        public UnRegRequest(ECSMS.Channel.LingKaiService.UnRegRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnRegRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        public UnRegRequestBody() {
        }
        
        public UnRegRequestBody(string CorpID, string Pwd) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnRegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnRegResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.UnRegResponseBody Body;
        
        public UnRegResponse() {
        }
        
        public UnRegResponse(ECSMS.Channel.LingKaiService.UnRegResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnRegResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UnRegResult;
        
        public UnRegResponseBody() {
        }
        
        public UnRegResponseBody(int UnRegResult) {
            this.UnRegResult = UnRegResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeUp", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.ChargeUpRequestBody Body;
        
        public ChargeUpRequest() {
        }
        
        public ChargeUpRequest(ECSMS.Channel.LingKaiService.ChargeUpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeUpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CardNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CardPwd;
        
        public ChargeUpRequestBody() {
        }
        
        public ChargeUpRequestBody(string CorpID, string Pwd, string CardNo, string CardPwd) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
            this.CardNo = CardNo;
            this.CardPwd = CardPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChargeUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChargeUpResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.ChargeUpResponseBody Body;
        
        public ChargeUpResponse() {
        }
        
        public ChargeUpResponse(ECSMS.Channel.LingKaiService.ChargeUpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChargeUpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChargeUpResult;
        
        public ChargeUpResponseBody() {
        }
        
        public ChargeUpResponseBody(int ChargeUpResult) {
            this.ChargeUpResult = ChargeUpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowMessage", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.ShowMessageRequestBody Body;
        
        public ShowMessageRequest() {
        }
        
        public ShowMessageRequest(ECSMS.Channel.LingKaiService.ShowMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        public ShowMessageRequestBody() {
        }
        
        public ShowMessageRequestBody(string CorpID, string Pwd) {
            this.CorpID = CorpID;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.ShowMessageResponseBody Body;
        
        public ShowMessageResponse() {
        }
        
        public ShowMessageResponse(ECSMS.Channel.LingKaiService.ShowMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowMessageResult;
        
        public ShowMessageResponseBody() {
        }
        
        public ShowMessageResponseBody(string ShowMessageResult) {
            this.ShowMessageResult = ShowMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVer", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetVerRequestBody Body;
        
        public GetVerRequest() {
        }
        
        public GetVerRequest(ECSMS.Channel.LingKaiService.GetVerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ver;
        
        public GetVerRequestBody() {
        }
        
        public GetVerRequestBody(string Ver) {
            this.Ver = Ver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVerResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetVerResponseBody Body;
        
        public GetVerResponse() {
        }
        
        public GetVerResponse(ECSMS.Channel.LingKaiService.GetVerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVerResult;
        
        public GetVerResponseBody() {
        }
        
        public GetVerResponseBody(string GetVerResult) {
            this.GetVerResult = GetVerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpdateDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpdateData", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetUpdateDataRequestBody Body;
        
        public GetUpdateDataRequest() {
        }
        
        public GetUpdateDataRequest(ECSMS.Channel.LingKaiService.GetUpdateDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUpdateDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ver;
        
        public GetUpdateDataRequestBody() {
        }
        
        public GetUpdateDataRequestBody(string Ver) {
            this.Ver = Ver;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUpdateDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUpdateDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ECSMS.Channel.LingKaiService.GetUpdateDataResponseBody Body;
        
        public GetUpdateDataResponse() {
        }
        
        public GetUpdateDataResponse(ECSMS.Channel.LingKaiService.GetUpdateDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUpdateDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetUpdateDataResult;
        
        public GetUpdateDataResponseBody() {
        }
        
        public GetUpdateDataResponseBody(System.Xml.Linq.XElement GetUpdateDataResult) {
            this.GetUpdateDataResult = GetUpdateDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LinkWSSoapChannel : ECSMS.Channel.LingKaiService.LinkWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkWSSoapClient : System.ServiceModel.ClientBase<ECSMS.Channel.LingKaiService.LinkWSSoap>, ECSMS.Channel.LingKaiService.LinkWSSoap {
        
        public LinkWSSoapClient() {
        }
        
        public LinkWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LinkWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LinkWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.WapSendResponse ECSMS.Channel.LingKaiService.LinkWSSoap.WapSend(ECSMS.Channel.LingKaiService.WapSendRequest request) {
            return base.Channel.WapSend(request);
        }
        
        public int WapSend(string CorpID, string Pwd, string Mobile, string WebSite, string Title, string cell) {
            ECSMS.Channel.LingKaiService.WapSendRequest inValue = new ECSMS.Channel.LingKaiService.WapSendRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.WapSendRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.Mobile = Mobile;
            inValue.Body.WebSite = WebSite;
            inValue.Body.Title = Title;
            inValue.Body.cell = cell;
            ECSMS.Channel.LingKaiService.WapSendResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).WapSend(inValue);
            return retVal.Body.WapSendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.GetReportFailResponse ECSMS.Channel.LingKaiService.LinkWSSoap.GetReportFail(ECSMS.Channel.LingKaiService.GetReportFailRequest request) {
            return base.Channel.GetReportFail(request);
        }
        
        public string GetReportFail(string CorpID, string Pwd, string cell) {
            ECSMS.Channel.LingKaiService.GetReportFailRequest inValue = new ECSMS.Channel.LingKaiService.GetReportFailRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.GetReportFailRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.cell = cell;
            ECSMS.Channel.LingKaiService.GetReportFailResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).GetReportFail(inValue);
            return retVal.Body.GetReportFailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.BatchSendResponse ECSMS.Channel.LingKaiService.LinkWSSoap.BatchSend(ECSMS.Channel.LingKaiService.BatchSendRequest request) {
            return base.Channel.BatchSend(request);
        }
        
        public int BatchSend(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            ECSMS.Channel.LingKaiService.BatchSendRequest inValue = new ECSMS.Channel.LingKaiService.BatchSendRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.BatchSendRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.Cell = Cell;
            inValue.Body.SendTime = SendTime;
            ECSMS.Channel.LingKaiService.BatchSendResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).BatchSend(inValue);
            return retVal.Body.BatchSendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.RegResponse ECSMS.Channel.LingKaiService.LinkWSSoap.Reg(ECSMS.Channel.LingKaiService.RegRequest request) {
            return base.Channel.Reg(request);
        }
        
        public int Reg(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo) {
            ECSMS.Channel.LingKaiService.RegRequest inValue = new ECSMS.Channel.LingKaiService.RegRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.RegRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.CorpName = CorpName;
            inValue.Body.LinkMan = LinkMan;
            inValue.Body.Tel = Tel;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Email = Email;
            inValue.Body.Memo = Memo;
            ECSMS.Channel.LingKaiService.RegResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).Reg(inValue);
            return retVal.Body.RegResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.UpdPwdResponse ECSMS.Channel.LingKaiService.LinkWSSoap.UpdPwd(ECSMS.Channel.LingKaiService.UpdPwdRequest request) {
            return base.Channel.UpdPwd(request);
        }
        
        public int UpdPwd(string CorpID, string Pwd, string NewPwd) {
            ECSMS.Channel.LingKaiService.UpdPwdRequest inValue = new ECSMS.Channel.LingKaiService.UpdPwdRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.UpdPwdRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.NewPwd = NewPwd;
            ECSMS.Channel.LingKaiService.UpdPwdResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).UpdPwd(inValue);
            return retVal.Body.UpdPwdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.UpdRegResponse ECSMS.Channel.LingKaiService.LinkWSSoap.UpdReg(ECSMS.Channel.LingKaiService.UpdRegRequest request) {
            return base.Channel.UpdReg(request);
        }
        
        public int UpdReg(string CorpID, string Pwd, string CorpName, string LinkMan, string Tel, string Mobile, string Email, string Memo) {
            ECSMS.Channel.LingKaiService.UpdRegRequest inValue = new ECSMS.Channel.LingKaiService.UpdRegRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.UpdRegRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.CorpName = CorpName;
            inValue.Body.LinkMan = LinkMan;
            inValue.Body.Tel = Tel;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Email = Email;
            inValue.Body.Memo = Memo;
            ECSMS.Channel.LingKaiService.UpdRegResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).UpdReg(inValue);
            return retVal.Body.UpdRegResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.SelSumResponse ECSMS.Channel.LingKaiService.LinkWSSoap.SelSum(ECSMS.Channel.LingKaiService.SelSumRequest request) {
            return base.Channel.SelSum(request);
        }
        
        public int SelSum(string CorpID, string Pwd) {
            ECSMS.Channel.LingKaiService.SelSumRequest inValue = new ECSMS.Channel.LingKaiService.SelSumRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.SelSumRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            ECSMS.Channel.LingKaiService.SelSumResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).SelSum(inValue);
            return retVal.Body.SelSumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.SendResponse ECSMS.Channel.LingKaiService.LinkWSSoap.Send(ECSMS.Channel.LingKaiService.SendRequest request) {
            return base.Channel.Send(request);
        }
        
        public int Send(string CorpID, string Pwd, string Mobile, string Content, string Cell, string SendTime) {
            ECSMS.Channel.LingKaiService.SendRequest inValue = new ECSMS.Channel.LingKaiService.SendRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.SendRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.Cell = Cell;
            inValue.Body.SendTime = SendTime;
            ECSMS.Channel.LingKaiService.SendResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).Send(inValue);
            return retVal.Body.SendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.GetResponse ECSMS.Channel.LingKaiService.LinkWSSoap.Get(ECSMS.Channel.LingKaiService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public string Get(string CorpID, string Pwd) {
            ECSMS.Channel.LingKaiService.GetRequest inValue = new ECSMS.Channel.LingKaiService.GetRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.GetRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            ECSMS.Channel.LingKaiService.GetResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.UnRegResponse ECSMS.Channel.LingKaiService.LinkWSSoap.UnReg(ECSMS.Channel.LingKaiService.UnRegRequest request) {
            return base.Channel.UnReg(request);
        }
        
        public int UnReg(string CorpID, string Pwd) {
            ECSMS.Channel.LingKaiService.UnRegRequest inValue = new ECSMS.Channel.LingKaiService.UnRegRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.UnRegRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            ECSMS.Channel.LingKaiService.UnRegResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).UnReg(inValue);
            return retVal.Body.UnRegResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.ChargeUpResponse ECSMS.Channel.LingKaiService.LinkWSSoap.ChargeUp(ECSMS.Channel.LingKaiService.ChargeUpRequest request) {
            return base.Channel.ChargeUp(request);
        }
        
        public int ChargeUp(string CorpID, string Pwd, string CardNo, string CardPwd) {
            ECSMS.Channel.LingKaiService.ChargeUpRequest inValue = new ECSMS.Channel.LingKaiService.ChargeUpRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.ChargeUpRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            inValue.Body.CardNo = CardNo;
            inValue.Body.CardPwd = CardPwd;
            ECSMS.Channel.LingKaiService.ChargeUpResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).ChargeUp(inValue);
            return retVal.Body.ChargeUpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.ShowMessageResponse ECSMS.Channel.LingKaiService.LinkWSSoap.ShowMessage(ECSMS.Channel.LingKaiService.ShowMessageRequest request) {
            return base.Channel.ShowMessage(request);
        }
        
        public string ShowMessage(string CorpID, string Pwd) {
            ECSMS.Channel.LingKaiService.ShowMessageRequest inValue = new ECSMS.Channel.LingKaiService.ShowMessageRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.ShowMessageRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.Pwd = Pwd;
            ECSMS.Channel.LingKaiService.ShowMessageResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).ShowMessage(inValue);
            return retVal.Body.ShowMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.GetVerResponse ECSMS.Channel.LingKaiService.LinkWSSoap.GetVer(ECSMS.Channel.LingKaiService.GetVerRequest request) {
            return base.Channel.GetVer(request);
        }
        
        public string GetVer(string Ver) {
            ECSMS.Channel.LingKaiService.GetVerRequest inValue = new ECSMS.Channel.LingKaiService.GetVerRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.GetVerRequestBody();
            inValue.Body.Ver = Ver;
            ECSMS.Channel.LingKaiService.GetVerResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).GetVer(inValue);
            return retVal.Body.GetVerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ECSMS.Channel.LingKaiService.GetUpdateDataResponse ECSMS.Channel.LingKaiService.LinkWSSoap.GetUpdateData(ECSMS.Channel.LingKaiService.GetUpdateDataRequest request) {
            return base.Channel.GetUpdateData(request);
        }
        
        public System.Xml.Linq.XElement GetUpdateData(string Ver) {
            ECSMS.Channel.LingKaiService.GetUpdateDataRequest inValue = new ECSMS.Channel.LingKaiService.GetUpdateDataRequest();
            inValue.Body = new ECSMS.Channel.LingKaiService.GetUpdateDataRequestBody();
            inValue.Body.Ver = Ver;
            ECSMS.Channel.LingKaiService.GetUpdateDataResponse retVal = ((ECSMS.Channel.LingKaiService.LinkWSSoap)(this)).GetUpdateData(inValue);
            return retVal.Body.GetUpdateDataResult;
        }
    }
}
